name: tests

on:
  - push
  - pull_request

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
        django: [<2.3, <3.1, <3.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Python dependencies
        run: |
          pip install --upgrade pipenv
          pipenv install $DJANGO
          pipenv install .
          pipenv install --dev six pytest pytest-django pytest-selenium selenium
      - name: Test
        run: |
          DJANGO_SETTINGS_MODULE=settings xvfb-run pipenv run python setup.py test
